name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup and Build Backend App
        working-directory: backend
        run: |
          npm i

      - name: Testing Backend App
        working-directory: backend
        run: npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: 21ecc255-7fc3-4731-bde5-fc377b0725bc

      - name: Setup and Build Frontend App
        working-directory: frontend
        run: |
          npm i
          npm run build
